---
- hosts: localhost
  gather_facts: false
  
  vars:
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      
  tasks:
    - name: Launch a job on AWX
      awx.awx.export:
        controller_host: 'awx-lb.zero-days.nl'
        controller_username: "{{ username }}"
        controller_password: "{{ password }}"
        validate_certs: false
#        workflow_job_templates: 'all'
        job_templates: 'all'
      register: awx_job_result

    - name: Print the results
      debug:
        msg: "{{ awx_job_result }}"
