---
- name: CALL WORKFLOW
  connection: local
  gather_facts: False

  vars:
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
  
  tasks:
    - name: CALL WINDOWS WORKFLOW
      ansible.builtin.uri:
        url: "http://awx.zero-days.nl:10445/api/v2/workflow_job_templates/15/launch/"
        method: POST
        user: "{{ username }}"
        password: "{{ password }}"
        status_code: 201, 302, 200
        headers:
            Content-Type: "application/json"
        body:
          {
              "extra_vars": {
                "tenant": "{{ tenant }}",
                "anp": "{{ anp_name }}",
                "epg": "{{ epg_name }}",
                "subnet": "{{ subnet }}"
              }
          }
        body_format: json
        validate_certs: no
      when: os == "windows"

    - name: CALL LINUX WORKFLOW
      ansible.builtin.uri:
        url: "http://awx.zero-days.nl:10445/api/v2/workflow_job_templates/21/launch/"
        method: POST
        user: "{{ username }}"
        password: "{{ password }}"
        status_code: 201, 302, 200
        headers:
            Content-Type: "application/json"
        body:
          {
              "extra_vars": {
                "tenant": "{{ tenant }}",
                "anp": "{{ anp_name }}",
                "epg": "{{ epg_name }}",
                "subnet": "{{ subnet }}"
              }
          }
        body_format: json
        validate_certs: no
      when: os == "linux"
