---
- name: List all extra vars
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Load the YAML string into a dictionary
      set_fact:
        parsed_vm_definitions: "{{ vm_definitions | from_yaml }}"

    - name: Extract vm_tenant
      set_fact:
        vm_tenant: "{{ parsed_vm_definitions.vm_definitions[0].vm_tenant }}"

    - name: Show the extracted vm_tenant
      debug:
        msg: "vm_tenant is {{ vm_tenant }}"