---
###########################################################################################################
# Create Palo Alto firewall object
###########################################################################################################
#
# This script performs the following steps:
# - Create Palo Alto network object
#
# Requirements:
# - ansible>=2.15.0
# - paloaltonetworks.panos ansible module (ansible-galaxy collection install paloaltonetworks.panos)
# - Python module pan-python (pip install pan-python)
#
###########################################################################################################

- name: CREATE PALO ALTO OBJECT
  hosts: "firewall"
  connection: local
  gather_facts: False

  vars:
    provider:
      ip_address: "{{ inventory_hostname }}"
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'

  tasks:
    - name: CREATE NETWORK OBJECT
      paloaltonetworks.panos.panos_op:
        provider: '{{ provider }}'
#        cmd: '<show><rule-hit-count><vsys><vsys-name>vsys1</vsys-name><rule-base><security><rules><all/></rules></security></rule-base></vsys></rule-hit-count>'
#        cmd: 'show rule-hit-count vsys vsys-name vsys1 rule-base security rules all'
        cmd: 'show interface all'
#        cmd_is_xml: true
      register: sec_hitcount

    - name: DEBUG 
      debug:
        var: sec_hitcount

# TODO CONVERT FROM FIREWALL TO PANORAMA AND COMMIT
 #   - name: COMMIT CHANGES BY API-USER ON PANORAMA
 #     paloaltonetworks.panos.panos_commit_panorama:
 #       provider: '{{ provider }}'
 #       admins: ['api-user']
 #       description: "ICD#{{ ticket_num }}"
