---
###########################################################################################################
# Palo Alto proxy URL access (WIP)
###########################################################################################################
#
# This script performs the following steps:
# - Palo Alto proxy URL access
#
# Requirements:
# - ansible>=2.15.0
# - paloaltonetworks.panos ansible module (ansible-galaxy collection install paloaltonetworks.panos)
# - Python module pan-python (pip install pan-python)
#
# This playbook performs the following steps:
# - Validate if entered URL's are valid Palo Alto URL format
#
# - Query Panorama if a standard named URL category for the EPG exists (eg uc_bd_application_function)
#    - Add URL to the standard named URL category if found
#
# - If no standard named URL category is found then query the security rules to see if a security rule
#   exists for our source_object that might use a non-standard named URL category list
#   (eg NOT uc_bd_application_function but perhaps uc_application or something else)
#
#    - If no security rule is found for source_object then a new URL category and security rule are created
#      using standard URL category name as we can safely assume the service has no proxy access yet
#    - If a security rule is found for the source_object, extract the used URL category and add URL to it
#      Abort if we find more than one URL category on the security rule - Non-deterministic condition!
#
###########################################################################################################

- name: Palo Alto proxy URL access
  hosts: "panorama"
  connection: local
  gather_facts: False

  vars:
    validate_url: true # set to true to validate if URL's are according to Palo Alto required format
    perform_commit: true # set to false if you do not want the playbook to perform actual Panorama commits
    debug: false # set to true to show extra debug information
    lookup_tags: true # set to true to attempt policy rule tag lookup
    conditional_rule_placement: true # set to true to attempt placing new rules in conditional order
    provider:
      ip_address: "{{ inventory_hostname }}"
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'

  tasks:
    - name: Convert input URL list string to list if needed
      ansible.builtin.set_fact:
        request_url_list: "{{ url_list | from_yaml }}"
      when: url_list is string

    - name: Validate Palo Alto URL list entries
      # This function checks if the URL's provided in the request_url_list URL list are valid Palo Alto accepted URL's
      block:

        - name: Validate Palo Alto URL list entries [1/5] - Initialize lists
          ansible.builtin.set_fact:
            valid_urls: []
            invalid_urls: []

        - name: Validate Palo Alto URL list entries [2/5] - Categorize URLs
          vars:
            # Checks to run against URL while looping through request_url_list
            starts_with_protocol: "{{ item.startswith('http://') or item.startswith('https://') }}" # URL cannot begin with protocol like http(s)
            has_invalid_chars: "{{ ' ' in item }}" # URL has invalid characters
            is_ip: "{{ item | regex_search('^\\d{1,3}(\\.\\d{1,3}){3}$') is not none }}" # URL is an IP address
            caret_ok: "{{ not ('/^' in item) }}" # Incorrect use of caret
          ansible.builtin.set_fact:
            valid_urls: "{{ valid_urls + [item] }}"
            invalid_urls: "{{ invalid_urls + [item] }}"
          loop: "{{ request_url_list }}"
          loop_control:
            label: "{{ item }}"
          when: not (starts_with_protocol or has_invalid_chars or is_ip or not caret_ok)

        - name: Validate Palo Alto URL list entries [3/5] - Collect invalid URLs
          ansible.builtin.set_fact:
            invalid_urls: "{{ request_url_list | difference(valid_urls) }}"

        - name: Validate Palo Alto URL list entries [4/5] - Fail if invalid URLs exist
          ansible.builtin.fail:
            msg: |
              Invalid Palo Alto URLs found:
              {{ invalid_urls | to_nice_yaml }}
          when: invalid_urls | length > 0

        - name: Validate Palo Alto URL list entries [5/5] - Show valid URLs
          ansible.builtin.debug:
            msg: |
              Valid Palo Alto URLs:
              {{ valid_urls | to_nice_yaml }}

      when: validate_url

    - name: Find firewall object based on input variable [1/4] - Strip bd_ or epg_ from input epg_name variable
      ansible.builtin.set_fact:
        address_object_name: >-
          {{ epg_name | regex_replace('^(bd_|epg_)', '') }}

    - name: Find firewall object based on input variable [2/4] - Get address objects from Panorama
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ provider }}"
        state: 'gathered'
        gathered_filter: '*'
      register: gathered_objects

    - name: Find firewall object based on input variable [3/4] - Search for address object
      ansible.builtin.set_fact:
        source_object: >-
          {{ gathered_objects.gathered
            | selectattr('name', 'search', address_object_name)
            | map(attribute='name')
            | list }}

    - name: Find firewall object based on input variable [4/4] - Fail if no address object was found
      ansible.builtin.fail:
        msg: >-
          No Palo Alto address_object found matching '{{ address_object_name }}'
          (derived from epg_name='{{ epg_name }}').
      when: source_object | length == 0

    - name: Set URL Category name
      ansible.builtin.set_fact:
        uc_name: "uc_{{ source_object[0].split(' - ')[0] }}"

    - name: Handle Palo Alto field limit [1/3] - Set original uc_name before truncation
      ansible.builtin.set_fact:
        original_uc_name: "{{ 'uc_' + source_object[0].split(' - ')[0] }}"

    - name: Handle Palo Alto field limit [2/3] - Truncate uc_name to max 31 characters
      ansible.builtin.set_fact:
        uc_name: "{{ original_uc_name[:31] }}"

    - name: Handle Palo Alto field limit [3/3] - Warn if uc_name was truncated
      ansible.builtin.debug:
        msg: "WARNING: uc_name was truncated from {{ original_uc_name }} to {{ uc_name }}"
      when: original_uc_name | length > 31

    - name: Gather all custom URL categories
      # Check if we have a standard named URL category list (uc_bd_example)
      paloaltonetworks.panos.panos_custom_url_category:
        provider: "{{ provider }}"
        state: 'gathered'
        gathered_filter: '*'
      register: gathered_categories

    - name: Check if category '{{ uc_name }}' exists
      ansible.builtin.set_fact:
        url_category_exists: >-
          {{ uc_name in gathered_categories.gathered | map(attribute='name') | list }}

    - name: Add URL to named URL category and set commit
      block:

        - name: Add URL to standard named URL category (MERGED)
          paloaltonetworks.panos.panos_custom_url_category:
            provider: "{{ provider }}"
            name: "{{ uc_name }}"
            url_value: "{{ request_url_list }}"
            state: "merged"

        - name: Set commit needed to true
          ansible.builtin.set_fact:
            commit: true
          when: perform_commit

      when: url_category_exists

    - name: Query security rules for URL category
      # If no standard named URL category is found (not exists), query security rules for URL category
      block:

        - name: Get all security rules from the device
          paloaltonetworks.panos.panos_security_rule:
            provider: "{{ provider }}"
            device_group: "ss-external"
            state: 'gathered'
            gathered_filter: '*'
          register: security_rules

        - name: DEBUG - Display matching rules
          ansible.builtin.debug:
            var: security_rules
          when: debug

        - name: Filter rules with source object "{{ source_object | first }}"
          ansible.builtin.set_fact:
            filtered_rules: >-
              {{
                security_rules.gathered
                | selectattr('source_ip', 'defined')
                | selectattr('source_ip', 'contains', (source_object | first))
                | list
              }}
          # TODO: Check doc on source_ip vs source object

        - name: DEBUG - Display matching rules
          ansible.builtin.debug:
            var: filtered_rules
          when: debug

      when: not url_category_exists

    - name: Add URL to a new URL category or existing category extracted from security rules
      block:

        - name: Create proxy rule if no existing rule is found
          # If no proxy security rule is found for the requested source object then create a new URL category and a new proxy firewall security rule
          block:

            - name: Create a new URL category with requested URL
              paloaltonetworks.panos.panos_custom_url_category:
                provider: "{{ provider }}"
                name: "{{ uc_name }}"
                url_value: "{{ request_url_list }}"
                state: "present"

            - name: Set new URL category to ALERT under the url-filtering profile
              # No Ansible module available to directly modify url-filtering, having to use panos_config_element with xpath and element
              paloaltonetworks.panos.panos_config_element:
                provider: "{{ provider }}"
                xpath: "/config/shared/profiles/url-filtering"
                element: |-
                  <entry name="strict-proxy-bp">
                    <credential-enforcement>
                      <alert>
                        <member>{{ uc_name }}</member>
                      </alert>
                    </credential-enforcement>
                    <alert>
                      <member>{{ uc_name }}</member>
                    </alert>
                  </entry>

            - name: Find tag based on input variable
              when: lookup_tags
              block:

                - name: Find tag based on input variable - Get our application name from the EPG name
                  ansible.builtin.set_fact:
                    tag_object_name: "{{ source_object[0].split('_')[1] }}"

                - name: Find tag based on input variable - Get tag objects from Panorama
                  paloaltonetworks.panos.panos_tag_object:
                    provider: "{{ provider }}"
                    state: 'gathered'
                    gathered_filter: '*'
                  register: gathered_tag_objects

                - name: Find tag based on input variable - Search for tag object
                  ansible.builtin.set_fact:
                    tag_object: >-
                      {{ gathered_tag_objects.gathered
                        | selectattr('name', 'search', tag_object_name)
                        | map(attribute='name')
                        | list }}

                - name: Find tag based on input variable - Detect environment from epg name
                  ansible.builtin.set_fact:
                    env_tag: "{{ (epg_name.split('_') | intersect(['dev','tst','acc','prd']) | first) | default('') }}"

                - name: Attempt conditional rule placement
                  when: conditional_rule_placement
                  block:

                    - name: EXP Filter rules get all the rules with a group_tag matching tag object
                      ansible.builtin.set_fact:
                        tag_filtered_rules: >-
                          {{
                            security_rules.gathered
                            | rejectattr('group_tag', 'equalto', none)
                            | selectattr('group_tag', 'equalto', (tag_object | first))
                            | list
                          }}
                      when:
                        - tag_object is defined
                        - (tag_object | length) > 0

                - name: EXP Get the last rule name from tag_filtered_rules list
                  ansible.builtin.set_fact:
                    last_rule_name: "{{ (tag_filtered_rules | last).name }}"
                  when: tag_filtered_rules | length > 0

            - name: Create proxy rule
              paloaltonetworks.panos.panos_security_rule:
                provider: "{{ provider }}"
                device_group: "ss-external"
                rule_name: "{{ source_object[0].split(' - ')[0] }} to web"
                description: "{{ source_object[0].split(' - ')[0] }} to web"
                tag_name: >-
                  {{
                    ['sddc - automated']
                    + ([env_tag] if (env_tag | default('') | string | trim | length) > 0 else [])
                    + ([tag_object | first] if (tag_object | default([]) | length) > 0 else [])
                  }}
                group_tag: "{{ (tag_object | default([]) | first | default('')) | string | trim }}"
                source_zone: ['all']
                source_ip: "{{ source_object[0] }}"
                destination_zone: ['all']
                destination_ip: ['any']
                service: ['service-https']
                category: "{{ uc_name }}"
                action: 'allow'

            - name: Set commit needed to true
              ansible.builtin.set_fact:
                commit: true
              when: perform_commit

            - name: Set push needed to true
              ansible.builtin.set_fact:
                push: true
              when: perform_commit

          when: filtered_rules is not defined or filtered_rules | length == 0

        - name: If a proxy rule is found then retrieve URL category and add URL to that URL category
          # If a proxy security rule is found then retrieve the URL category used on the rule and add the requested URL to the URL category list
          block:

            - name: Initialize list of categories
              ansible.builtin.set_fact:
                url_categories: []

            - name: Append category to list
              ansible.builtin.set_fact:
                url_categories: "{{ url_categories + [item.category | join(', ')] }}"
              loop: "{{ filtered_rules }}"

            - name: DEBUG - Display all categories
              ansible.builtin.debug:
                var: url_categories
              when: debug

            - name: Fail if more than one URL category is found for our source object
              ansible.builtin.fail:
                msg: "More than one URL category found in rule, unable to determine which URL category list to use: {{ url_categories }}"
              when: url_categories | length > 1

            - name: Add URL to retrieved URL category using merged state
              paloaltonetworks.panos.panos_custom_url_category:
                provider: "{{ provider }}"
                name: "{{ url_categories[0] }}"
                url_value: "{{ request_url_list }}"
                state: "merged"

            - name: Set commit needed to true
              ansible.builtin.set_fact:
                commit: true
              when: perform_commit

          when: filtered_rules is defined and filtered_rules is not none and filtered_rules | length > 0

      when: not url_category_exists

    - name: Commit changes by ansible user when commit is needed + CHECK PUSH!
      # Commit changes when commit flag has been set
      paloaltonetworks.panos.panos_commit_panorama:
        provider: "{{ provider }}"
        admins: ['{{ provider.username }}']
        description: "{{ ticket_num | default('Commit from Ansible orchestrator - Proxy') }}"  # Optional: leave empty if not provided
      when: commit

#    - name: Push device group configs
#      paloaltonetworks.panos.panos_commit_push:
#        provider: "{{ provider }}"
#        admins: ['{{ provider.username }}']
#        style: "device group"
#        name: "ss-external"
#        description: "Push from Ansible orchestrator - Proxy"
#      when: push