---
###########################################################################################################
# Create Palo Alto firewall object
###########################################################################################################
#
# This script performs the following steps:
# - Create Palo Alto network object
#
# Requirements:
# - ansible>=2.15.0
# - paloaltonetworks.panos ansible module (ansible-galaxy collection install paloaltonetworks.panos)
# - Python module pan-python (pip install pan-python) when using panos_module, else use API
#
# Notes:
# - Set use_panos variable to True to use ansible module instead of API
#
###########################################################################################################

- name: CREATE PALO ALTO OBJECT
  hosts: "panorama"
  connection: local
  gather_facts: False

  vars:
    source_object: "bd_myapp1_lb02_prd - 10.221.9.240_28"
    provider:
      ip_address: "{{ inventory_hostname }}"
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'

  tasks:
    - name: Get all security rules from the device
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        state: 'gathered'
        gathered_filter: '*'
      register: security_rules

    - name: Display matching rules
      debug:
        var: security_rules

    - name: Filter rules with source object "{{ source_object }}"
      set_fact:
        filtered_rules: >-
          {{
            security_rules.rules | selectattr('source', 'defined') 
                                 | selectattr('source', 'contains', source_object)
                                 | list
          }}

    - name: Display matching rules
      debug:
        var: filtered_rules