---
###########################################################################################################
# Create Palo Alto firewall object
###########################################################################################################
#
# This script performs the following steps:
# - Create Palo Alto network object
#
# Requirements:
# - ansible>=2.15.0
# - paloaltonetworks.panos ansible module (ansible-galaxy collection install paloaltonetworks.panos)
# - Python module pan-python (pip install pan-python)
#
###########################################################################################################

- name: CREATE PALO ALTO OBJECT
  hosts: "panorama"
  connection: local
  gather_facts: False

  vars:
    provider:
      ip_address: "{{ inventory_hostname }}"
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'

  tasks:
    - name: FAIL IF MANDATORY VARS ARE MISSING
      fail:
        msg: "One or more required variables are undefined!"
      when: >
        application is not defined or
        cust_environment is not defined or
        subnet is not defined

    - name: SET COMMON NAMES 
      set_fact:
        obj_name: "bd_{{ application }}{{ '_' + function if function is defined and function | length > 0 else '' }}_{{ cust_environment }} - {{ subnet | replace('/','_') }}"

    - name: GET API KEY
      ansible.builtin.uri:
        url: "https://{{ provider.ip_address }}/api/?type=keygen&user={{ provider.username }}&password={{ provider.password }}"
        method: GET
        return_content: yes
        validate_certs: no
      register: key_response

    - name: EXTRACT API KEY FROM RESPONSE
      set_fact:
        api_key: "{{ key_response.content | regex_search('<key>([^<]+)</key>', '\\1') }}"

    - name: SHOW API KEY
      debug:
        var: api_key.0

    - name: Add address object via API
      ansible.builtin.uri:
 #       url: "https://{{ provider.ip_address }}/api/?key={{ api_key.0 }}&type=config&action=set&xpath=/config/shared/address/entry[@name='{{ obj_name }}'] &element=<ip-netmask>{{ subnet }}</ip-netmask>"
        url: "https://{{ provider.ip_address }}/api/"
        method: POST
        validate_certs: no
        body_format: form-urlencoded
        body:
          type: config
          action: set
          key: "{{ api_key.0 }}"
          xpath: "/config/shared/address"
          element: |
            <entry name='{{ obj_name }}'>
              <ip-netmask>{{ subnet }}</ip-netmask>
              <description>Web server for app</description>
            </entry>
      register: api_response

    - name: SHOW API RESPONSE
      debug:
        var: api_response

    - name: CREATE NETWORK OBJECT THROUGH PANOS MODULE
      block:

        - name: CREATE NETWORK OBJECT
          paloaltonetworks.panos.panos_address_object:
            provider: "{{ provider }}"
            name: "{{ obj_name }}"
            value: "{{ subnet }}"
            device_group: shared

        - name: COMMIT CHANGES BY API-USER ON PANORAMA
          paloaltonetworks.panos.panos_commit_panorama:
            provider: "{{ provider }}"
            admins: ['{{ provider.username }}']
            description: "ICD#{{ ticket_num }}"

      when: use_panos | default(false)