---
###########################################################################################################
# Create Palo Alto firewall object
###########################################################################################################
#
# This script performs the following steps:
# - Create Palo Alto network object
#
# Requirements:
# - ansible>=2.15.0
# - paloaltonetworks.panos ansible module (ansible-galaxy collection install paloaltonetworks.panos)
# - Python module pan-python (pip install pan-python)
#
###########################################################################################################

- name: CREATE PALO ALTO OBJECT
  hosts: "panorama"
  connection: local
  gather_facts: False

  vars:
    provider:
      ip_address: "{{ inventory_hostname }}"
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'

  tasks:
    - name: FAIL IF MANDATORY VARS ARE MISSING
      fail:
        msg: "One or more required variables are undefined!"
      when: >
        application is not defined or
        cust_environment is not defined or
        subnet is not defined

    - name: SET COMMON NAMES 
      set_fact:
        obj_name: "bd_{{ application }}{{ '_' + function if function is defined and function | length > 0 else '' }}_{{ cust_environment }} - {{ subnet | replace('/','_') }}"

    - name: CREATE NETWORK OBJECT
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ provider }}"
        name: "{{ obj_name }}"
        value: "{{ subnet }}"
        device_group: shared

    - name: COMMIT CHANGES BY API-USER ON PANORAMA
      paloaltonetworks.panos.panos_commit_panorama:
        provider: "{{ provider }}"
        admins: ['{{ provider.username }}']
        description: "ICD#{{ ticket_num }}"
