- name: SHOW MANUALLY SPECIFIED NETWORK
  ansible.builtin.debug:
    var: staticnetwork

- name: CREATE IPV4 NETWORK WITH INFOBLOX TEMPLATE
  infoblox.nios_modules.nios_network:
    network: "{{ staticnetwork }}"
    comment: "{{ bd_name }}"
    template: "onead_{{ subnetmask|int }}{% if not ( dhcp | bool ) %}_nodhcp{% endif %}"
    state: present
    provider: "{{ nios_provider }}"

- name: SET STAT THE NETWORK ADDRESS FOR FURTHER WORKFLOW
  ansible.builtin.set_stats:
    data:
      subnet: "{{ staticnetwork }}"

- name: RESTART INFOBLOX SERVICES INCLUDE
  ansible.builtin.include_tasks: includes/restart-infoblox-services.yml

- name: END PLAY - NOTHING MORE TO DO
  ansible.builtin.meta: end_play
