- name: SHOW MANUALLY SPECIFIED NETWORK
  debug:
    var: staticnetwork

- name: CREATE IPV4 NETWORK WITH INFOBLOX TEMPLATE
  infoblox.nios_modules.nios_network:
    network: "{{ staticnetwork }}"
    comment: "bd_{{ application }}{{ '_' + function if function is defined and function | length > 0 else '' }}_{{ cust_environment }}"
    template: "network{{ subnetmask }}{% if not dhcp %}_nodhcp{% endif %}"
    state: present
    provider: "{{ nios_provider }}"

- name: SET STAT THE NETWORK ADDRESS FOR FURTHER WORKFLOW
  ansible.builtin.set_stats:
    data:
      subnet: "{{ staticnetwork }}"

#    - name: RESTART INFOBLOX DHCP SERVICE
#      nios_restartservices:
#        services:
#          - DHCP
#        restart_option: RESTART_IF_NEEDED
#        mode: GROUPED
#        provider: "{{ nios_provider }}"

- name: END PLAY - NOTHING MORE TO DO
  ansible.builtin.meta: end_play
