- name: Query transceiver details
  hosts: apic
  connection: local
  gather_facts: false

  vars:
    username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
    password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
    sfp_pattern: "SFP-H25GB"

  tasks:
    - name: Query ethpmFcot objects from ACI
      cisco.aci.aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        path: /api/class/ethpmFcot.json
        method: get
      register: fcot_data

    - name: Get all physical interfaces (ethpmPhysIf)
      cisco.aci.aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        path: /api/class/ethpmPhysIf.json
        method: get
      register: physif_data

    # Build { "<.../phys>": "<operSt>" } safely using zip → dict
    - name: Build a lookup of interface DN → operState
      set_fact:
        oper_state_map: >-
          {{
            dict(
              (physif_data.imdata
                | map(attribute='ethpmPhysIf.attributes')
                | map('extract', 'dn'))
              | zip(
                  physif_data.imdata
                  | map(attribute='ethpmPhysIf.attributes')
                  | map('extract', 'operSt')
                )
            )
          }}

    # Walk matching transceivers and add an operSt from the physIf map
    - name: Collect transceivers that match pattern and merge with operState
      set_fact:
        transceiver_info: "{{ transceiver_info | default([]) + [ merged ] }}"
      vars:
        # For an fcot DN like ".../phys-[eth1/17]/phys/.../fcot"
        # derive the base phys DN: ".../phys-[eth1/17]/phys"
        base_phys_dn: "{{ (item.dn.split('/phys-')[0]) + '/phys' }}"
        merged: "{{ item | combine({'operSt': (oper_state_map[base_phys_dn] | default('unknown'))}) }}"
      loop: >-
        {{
          fcot_data.imdata
          | map(attribute='ethpmFcot.attributes')
          | selectattr('guiCiscoEID','search',sfp_pattern)
          | list
        }}

    - name: Show node/interface, SFP type, serial, and oper state
      debug:
        msg: >-
          {{
            transceiver_info
            | map('extract', 'dn') | zip(
                transceiver_info | map('extract','guiCiscoEID'),
                transceiver_info | map('extract','guiSN'),
                transceiver_info | map('extract','operSt')
              )
            | map('list')
            | list
          }}